#! /usr/bin/env python
# encoding: utf-8

bld.program(
    features = 'cxx test',
    source   = ['tables_tests.cpp'] + bld.path.ant_glob('src/*.cpp'),
    target   = 'tables_tests',
    use = ['tables', 'gtest', 'boost_includes'])
