#! /usr/bin/env python
# encoding: utf-8

bld.program(
    features='cxx',
    source=['creating_printing_table.cpp'] + bld.path.ant_glob('src/*.cpp'),
    target='creating_printing_table',
    use=['tables'])
